### ISSUE TITLE
Warning in composer

### ISSUE THREAD

**Issue by ju5tify** [yiisoft/yii2-composer#4]
Composer is now warning us that:
`The "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).`

**Comment by Besedin86** [comment]
:+1:

**Comment by samdark** [comment]
It's already fixed. We need to tag new release. @cebe can you do it?

**Comment by Besedin86** [comment]
@samdark , thanks!

**Comment by cebe** [comment]
will do.

**Comment by cebe** [comment]
done. https://github.com/yiisoft/yii2-composer/releases/tag/2.0.4

**Comment by AndresCL** [comment]
Still having this issue with 2.0.4.

The "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

**Comment by SilverFire** [comment]
Show your `composer -V` and `composer info -i`

**Comment by AndresCL** [comment]
I see. I've ran php -d suhosin.executor.include.whitelist=phar composer.phar self-update and updated vendor/yiisoft/yii2-composer with 2.0.4. Composer seems updated, but still 2.0.3.

> php -d suhosin.executor.include.whitelist=phar composer.phar -v
> Composer version 1.0-dev (8808638ea993633a6f9e5af240bfcf9714b9201a) 2016-02-10 15:36:42
> 
> php -d suhosin.executor.include.whitelist=phar composer.phar info -i
> yiisoft/yii2-composer        2.0.3   The composer plugin for Yii extension installer
>

**Comment by SilverFire** [comment]
Check your dependencies, maybe somewhere 2.0.3 is hard-coded.

**Comment by osCMattiFinn** [comment]
So how do we fix Composer?  It still throws the same error....

**Comment by cebe** [comment]
@osCMattiFinn what exactly are you talking about? The warning about composer-plugin-api or some other error?

**Comment by cebe** [comment]
The warning should be gone **after** update of yii2-composer extension to 2.0.4. So while upgrading it may still show up.

**Comment by mulupinar** [comment]
I still have the same error;  " _The "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example)._ "

- I installed new Composer
- and updated composer via " _composer self-update_ "
- and ı ran following command ; " _composer global require "fxp/composer-asset-plugin:~1.1.1"_ "

but my problem continues.. Can you help me about this?

**Comment by cebe** [comment]
this is already fixed since last year, no idea why you see that message: https://github.com/francoispluchino/composer-asset-plugin/commit/a94f51db88af30f681ac395853f9c6c55fb3be23

**Comment by thogan** [comment]
I also have the same error; " The "fxp/composer-asset-plugin" plugin requires composer-plugin-api 1.0.0, this WILL break in the future and it should be fixed ASAP (require ^1.0 for example). "   And it fails to upgrade from the 2.0.6 advanced template.

**Comment by cebe** [comment]
this message is just a warning, it should not fail anything. please provide more information about the commands you are running and the error messages you see.

**Comment by mulupinar** [comment]
I solved this problem. You can delete fxp folder from vendor in your project path... @thogan

**Comment by mulupinar** [comment]
Thanks @cebe

**Comment by thogan** [comment]
Thanks @cebe, I should have checked.   The upgrade succeeded.

**Comment by karmrajzala** [comment]
This issue have occurred because of yii-composer version in composer.lock file is 2.0.3 version. It is not matching with remote repository. So may i change in composer.lock file from 2.0.3 to 2.0.4? Is it right way?

**Comment by samdark** [comment]
No. Change it in composer.json. Never touch composer.lock manually.

**Comment by cebe** [comment]
The correct way to updated is running `composer update yiisoft/yii2-composer`.

**Comment by nishadotcom** [comment]
Update the particular plugin solves the issue.

Thanks
